version: '3'

#### docker-compose up -d;
### This is only a test.  Keep calm and ISLE on.

services:
  isle-portainer: ## Renamed to avoid conflicts on systems/servers with portainer already running.
    image: portainer/portainer
    container_name: isle-portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - isle-internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=port-isle
      - "traefik.frontend.rule=Host:portainer.isle.localdomain;"

  mysql:
    # build:
    #   context: ./images/mysql
    image: islandoracollabgroup/isle-mysql:latest
    container_name: isle-mysql-ld
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    networks:
      - isle-internal
    volumes:
      - db-data-ld:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    labels:
      - traefik.enable=false

  fedora:
    # build:
    #   context: ./images/isle-fedora
    image: benjaminrosner/isle-fedora:development
    container_name: isle-fedora-ld
    networks:
      - isle-internal
    ports:
      - "8081:8080"
    tty: true
    depends_on:
      - mysql
      - solr
    volumes:
      - fed-data-ld:/usr/local/fedora/data
      - ./data/fedora/log/fedora:/usr/local/fedora/server/logs
      - ./data/fedora/log/tomcat:/usr/local/tomcat/logs
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=fedora
      - "traefik.frontend.rule=Host:isle.localdomain; PathPrefix: /fedora"

  solr:
    # build:
    #   context: ./images/isle-solr
    image: benjaminrosner/isle-solr:development
    container_name: isle-solr-ld
    networks:
      - isle-internal
    ports:
      - "8082:8080"
    tty: true
    depends_on:
      - mysql
    volumes:
      - solr-data-ld:/usr/local/solr
      - ./data/solr/logs:/usr/local/tomcat/logs
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=solr
      - "traefik.frontend.rule=Host:isle.localdomain; PathPrefix: /solr"

  image-services:
    # build:
    #   context: ./images/isle-imageservices
    image: benjaminrosner/isle-imageservices:development
    container_name: isle-images
    networks:
      - isle-internal
    depends_on:
      - apache
      - fedora
    ports:
      - "8083:8080"
    volumes:
      - ./data/img/logs:/usr/local/tomcat/logs
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=isle-images
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin: *" # Debug
      - "traefik.frontend.headers.customRequestHeaders=Access-Control-Allow-Origin: *" # Debug
      - "traefik.frontend.rule=Host:isle.localdomain,images.isle.localdomain; PathPrefix: /adore-djatoka, /cantaloupe"

  apache:
    # build:
    #   context: ./images/isle-apache
    image: benjaminrosner/isle-apache:development
    container_name: isle-apache-ld
    networks:
      - isle-internal
    tty: true
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - apache-data-ld:/var/www/html
      - ./data/apache/log:/var/log/apache2
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.backend=web
      - traefik.frontend.rule=Host:isle.localdomain;
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin: *" # Debug
      - "traefik.frontend.headers.customRequestHeaders=Access-Control-Allow-Origin: *" # Debug


  traefik:
    image: traefik:latest
    container_name: isle-proxy
    networks:
      isle-internal:
        aliases:
          - isle.localdomain
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/isle.localdomain:/certs/isle.localdomain
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:admin.isle.localdomain;

# Defined networks
networks:
  isle-internal:
  # isle-external:

volumes:
  db-data-ld:
  fed-data-ld:
  solr-data-ld:
  apache-data-ld:
  portainer_data:
