version: '3'

#### docker-compose up -d;
## Updated 2018-08-31 - Release 1.1.0

services:
  isle-portainer: ## Renamed to avoid conflicts on systems/servers with portainer already running.
    image: portainer/portainer
    container_name: isle-portainer-${CONTAINER_SHORT_ID}
    command: -H unix:///var/run/docker.sock --no-auth
    networks:
      - isle-internal
    ports:
      - "9010:9000" ## Remapped to avoid conflicts on systems/servers with portainer already running.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - isle-portainer-data:/data
    labels:
      - traefik.port=9000
      - traefik.backend=port-isle-${CONTAINER_SHORT_ID}
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:portainer.${BASE_DOMAIN};"

  mysql:
    # build:
    #   context: ./images/mysql
    image: islandoracollabgroup/isle-mysql:latest
    container_name: isle-mysql-${CONTAINER_SHORT_ID}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - isle-internal
    volumes:
      - isle-db-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  fedora:
    # build:
    #   context: ./images/isle-fedora
    image: benjaminrosner/isle-fedora:latest
    container_name: isle-fedora-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=768M
      - JAVA_MIN_MEM=128M
    networks:
      - isle-internal
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - solr
    volumes:
      - isle-fedora-data:/usr/local/fedora/data
      - ./logs/fedora/fcrepo:/usr/local/fedora/server/logs
      - ./logs/fedora/tomcat:/usr/local/tomcat/logs

  solr:
    # build:
    #   context: ./images/isle-solr
    image: benjaminrosner/isle-solr:latest
    container_name: isle-solr-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    networks:
      - isle-internal
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    volumes:
      - isle-solr-data:/usr/local/solr
      - ./logs/solr:/usr/local/tomcat/logs

  image-services:
    # build:
    #   context: ./images/isle-imageservices
    image: benjaminrosner/isle-imageservices:latest
    container_name: isle-images-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    networks:
      - isle-internal
    depends_on:
      - apache
      - fedora
    ports:
      - "8083:8080"
    volumes:
      - ./logs/imageservices:/usr/local/tomcat/logs
    labels:
      - traefik.backend=isle-imageservices-${CONTAINER_SHORT_ID}
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:images.${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"

  apache:
    # build:
    #   context: ./images/isle-apache
    image: benjaminrosner/isle-apache:latest
    container_name: isle-apache-${CONTAINER_SHORT_ID}
    environment:
      - PULL_ISLE_BUILD_TOOLS=true # Defaults to true.
    networks:
      isle-internal:
        aliases:
          - ${BASE_DOMAIN}
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - isle-apache-data:/var/www/html
      - ./logs/apache/httpd:/var/log/apache2
      - ./logs/apache/fits:/var/log/fits
    labels:
      - traefik.backend=isle-apache-${CONTAINER_SHORT_ID}
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"

  traefik:
    image: traefik:latest
    container_name: isle-proxy-${CONTAINER_SHORT_ID}
    networks:
      isle-internal:
      isle-external:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/traefik.toml
      - ./config/traefik/isle.localdomain:/certs/isle.localdomain
    labels:
      - traefik.backend=isle-proxy-${CONTAINER_SHORT_ID}
      - traefik.port=8080
      - traefik.enable=true
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};

# Defined networks
networks:
  isle-internal:
  isle-external:

volumes:
  isle-db-data:
  isle-fedora-data:
  isle-solr-data:
  isle-apache-data:
  isle-portainer-data:
