version: '3'

#### docker-compose up -d;
### This is only a test.

services:
  mysql:
    # build:
    #   context: ./mysql
    image: islandoracollabgroup/isle-mysql:latest
    container_name: isle-mysql-ld
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    networks:
      - isle-internal
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/dbdata:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    labels:
      - traefik.enable=false

  fedora:
    # build:
    #   context: ./images/isle-fedora
    image: benjaminrosner/isle-fedora:preRC
    container_name: isle-fedora-ld
    networks:
      - isle-internal
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysql
      - solr
    volumes:
      - ./data/fedora/fedora-data:/usr/local/fedora/data
      - ./data/fedora/log/fedora:/usr/local/fedora/server/logs
      - ./data/fedora/log/tomcat:/usr/local/tomcat/logs
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=fedora
      - "traefik.frontend.rule=Host:isle.localdomain; PathPrefix: /adore-djatoka/, /fedora/"

  solr:
    # build:
    #   context: ./images/isle-solr
    image: benjaminrosner/isle-solr:preRC
    container_name: isle-solr-ld
    networks:
      - isle-internal
    ports:
      - "8091:8080"
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./data/solr/collection1:/usr/local/solr/collection1/data
      - ./data/solr/logs:/usr/local/tomcat/logs
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=solr
      - "traefik.frontend.rule=Host:isle.localdomain; PathPrefix: /solr/"

  apache:
    # build:
    #   context: ./images/isle-apache
    image: benjaminrosner/isle-apache:preRC
    container_name: isle-apache-ld
    networks:
      - isle-internal
    tty: true
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - ./data/apache/webroot:/var/www/html
      - ./data/apache/log:/var/log/apache2
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.backend=web
      - traefik.frontend.rule=Host:isle.localdomain;

  traefik:
    image: traefik:latest
    networks:
      - isle-internal
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/isle.localdomain:/certs/isle.localdomain
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:admin.isle.localdomain;

  # proxy:
  #   # build:
  #   #   context: ./proxy
  #   image: islandoracollabgroup/isle-proxy:latest
  #   container_name: isle-proxy
  #   networks:
  #     isle-internal:
  #     isle-external:
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - mysql
  #     - fedora
  #     - solr
  #     - apache
  #   command: [nginx-debug, '-g', 'daemon off;']


# Defined networks
networks:
  isle-internal:
  # isle-external:

# volumes:
#   db-data-ld:
#   fed-data-ld:
#   solr-data-ld:
#   apache-data-ld:
